apiVersion: nais.io/v1alpha1
kind: Application

metadata:
  name: sif-vju-frontend
  labels:
    team: sif-bachelor
  namespace: sif-bachelor

spec:
  ingresses:
    - https://sif-vju.ansatt.dev.nav.no
  image: "{{image}}"
  port: 3000
  azure:
    application:
      enabled: true
      allowAllUsers: true
    sidecar:
      enabled: true
      autoLogin: true
  accessPolicy:
    outbound:
      rules:
        - application: sif-vju-backend
  resources:
    limits:
      cpu: 2000m
      memory: 512Mi
    requests:
      cpu: 50m
      memory: 64Mi
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 90
